apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:X4xm2QLtEYOKZ7Ym7+fM71pv5eA4/lblOcbkjqlfIpQ9H1M/uWILqAKpoBKqfTe5K+wMOC1tvQn9XcKdDWUS2fkLYmnujMl5MRvpAY0x1a7ZshdrLyWzaUa4iMU3C2PP4AKuYqVvJfNPBhssNhmad5jNTT1a0af7ni67zbRXIm5y0FrQQvb9oQmbwobl0KYjjhU3aoloiAhx0LWNq8OS5QHoj7OwUn2exJs2D81FsDGbQDdk9Dqe4x6FL2iTiPnmvSNkHfi15DtpXJi0MMOrj1M0eP30X9tNuM2nkBoB8B2/idL2kFUgcx+M3X0=,iv:pOxfIVTLLndS7IB6cdlDKGtvkMeGCsd0L9vsoNAu4HM=,tag:WHtZFgoJLHVg6dsuxR9Few==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age184xrgkw7sywm3p4q0gky2afpafea70aas4dp03rtduy3zpsrs99sjdp8ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNVhhWWF5eEpYM3RPbkdX
            dllWc2pQTE9jMUZ0OC8yU3JZd0FmYWs3dENvCkNzSGEwYUdhbTV2bmZFN2c5VDFN
            bXZXZksrdktLRHNtVWlGNGlhcjJtcnMKLS0tIDZDTDl3TnR5UXZ1SjhaSjRwRWxl
            Tm9XNkVnWTlLcFIxU2x4c25rUExubFEK0VFFZO1w2UUUyf5rysE+V4/rSogivpNK
            py8iN5OtJj1yTUTDbAI9vnyhTLMcVu0Eq3araBcTpQvENfT0hXJJ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T21:23:27Z"
    mac: ENC[AES256_GCM,data:WW4L8UsychCFsu37dn1fqMz0miTXnBa+F0lCrEFelJEmmxrUeKhHdO9xy0fsx5DZZkF7rI9RI0jOc8TQL0sh9nwq1FLnqu/oNw/Syvp2aokSoHGa2bjAA8Q8opeG/XHOQQOU1DEz0BukfUKwWD9iEN3cwTZXK4iZvNslsbI+4C4=,iv:IsejDTA2zPS0KTg4zk7wLCB95D6BY7xJnDlhqFp3NMA=,tag:z2BhMUlw/Lj+3qYj19+0Iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
