apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:8aJ9lSL72oI=,iv:5lSmKol8w/V2BlqS0DoWMQvRCMtYLZ7TMkrlWCavG9w=,tag:ZGzcCekGLQHJ6d4XPBVSbA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:YexCoHy228+u/oLMugN4o6SETMs9L5gSfzXTvCJ/bSBSyer8knIOYKLOGVr87a095UbwOR0AQyw=,iv:SptdrwgyubzhhGrJaM7eB90NlT1UrOZcUu0MAm2Idno=,tag:oM9YDs79L4+m/yQZ9u6vFQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age184xrgkw7sywm3p4q0gky2afpafea70aas4dp03rtduy3zpsrs99sjdp8ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiamY5d01RaFR0eVI0SlVB
            VU9lejBzUENrbUYvUXJyZzBxMm1SaVMxcVJNCmpURkppVUMzQW1TK1k5bHFadjZv
            S0o1YU1sZFNQMXZFYjVrOHkxTlFObW8KLS0tIDNjK2tyVm81T3JFN2lTVUF4ZjdH
            dmYzUGtSRjRObWRNZmNjMytER3NwQUUKQj9Wd2iQDPhHKP+xE5RUtfWBV6LcFENp
            1WVMgJqKIsMPt436nCoSzizPMw+kbPwxhGqr5uguxZBYxgrmwCZJzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T22:52:57Z"
    mac: ENC[AES256_GCM,data:khNmE4m4vUAxIHoJu7JA0t2v2yWQr7/Gem80oJm0RAze/vofA2lkOqbLfqoAJ+kgY/eM/Orq4GV2zxvpkPUBWNcWVmBT96/7CQq0ZbwalneTa1VO1QmZfK+og33YzpUvrb9KEytvGE5FqCpph2uFDqhbOIWE7Wu81xWQbrpEBk4=,iv:NioTNcbgX3zqwWM+Mx6fM6TLbkyFOqUPmsOgm2igbTE=,tag:IWgHfQmF1cJ950cFwD/cyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
